---
- name: upload ssh key to digital ocean
  digital_ocean:
    api_token="{{ secret.token }}"
    command=ssh
    state=present
    name="{{ secret.key.name }}"
    ssh_pub_key="{{ secret.key.pub }}"
  register: do_ssh

